### ISSUE TITLE
Use the GitHub API endpoint to transform Markdown into HTML

### ISSUE THREAD

**Issue by db0company** [Jucyio/Jucy#10]
- First load using marked (quick view)
- On click to display issue body, make a call to the GitHub endpoint to update the markdown correctly

**Comment by abbysmal** [comment]
I gave it a try (see dcfe9d7), it's clearly not perfect, see main.js, we don't get the repository needed for the gfm parser context, so it might be better if we can fix this. (see https://developer.github.com/v3/markdown/)
