### ISSUE TITLE
Find a way to determine the status of an issue (to display it differently)

### ISSUE THREAD

**Issue by db0company** [Jucyio/Jucy#5]
In Jucy contest, an issue can be:
- New (open without label ready)
- Ready (open with the label ready)
- Duplicate (closed with label duplicate)
- Rejected (closed with label rejected)
- Done (closed without label rejected or duplicate)

**Comment by abbysmal** [comment]
Commit 783b606 introduced state tagging for ideas views.
I had no idea on how you wanted exactly to retrieve the state, so for now, the template will get a dictionary containing a state key, which is either 'rejected', 'duplicate', 'ready', 'done' or 'new', and an issue key pointing to the corresponding issue object.
Tell me if you need something better. :)

**Comment by db0company** [comment]
Awesome! Exactly what I needed. Thanks.
