### ISSUE TITLE
Filter issues based on their statuses

### ISSUE THREAD

**Issue by db0company** [Jucyio/Jucy#8]
By default, if you're:
- a collaborator: you see first the "New" issues, then the "Ready" issues. You can decide to display the duplicate, rejected and done issues if you want.
- a visitor: you see the "Ready" issues only, which allows you to vote for them.

**Comment by abbysmal** [comment]
Commit 4ed525f introduced a starting point for that.
I modified some things in the templates, I'm not sure on how much it changed on your side so it would be nice if you were able to push your changes soon to allow me to go further.
Edit:
This commit broke what was changed yesterday: we no longer have an issue.issue thing, but now each kind of ideas (duplicate, ready, new, rejected, done) are inside a different list available in the context.
It might be simpler, or not, still not quite sure on how to do that properly.
